import React from 'react';

export const VaccinationSchedule: React.FC = () => {
    const vaccinationData = [
        [
            { text: 'HepB 1차', colSpan: 1 },
            {},
            { text: 'HepB 2차', colSpan: 1 },
            {},
            {},
            { text: 'HepB 3차', colSpan: 1 },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
        ],
        [
            {},
            { text: 'BCG 1회', colSpan: 1 },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
        ],
        [
            {},
            {},
            {},
            { text: 'DTaP 1차', colSpan: 1 },
            { text: 'DTaP 2차', colSpan: 1 },
            { text: 'DTaP 3차', colSpan: 1 },
            {},
            { text: 'DTaP 4차', colSpan: 2 },
            {},
            {},
            { text: 'DTaP 5차', colSpan: 2 },
            {},
            {},
        ],
        [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { text: 'Tdap/Td 6차', colSpan: 2 },
        ],
        [
            {},
            {},
            {},
            { text: 'IPV 1차', colSpan: 1 },
            { text: 'IPV 2차', colSpan: 1 },
            { text: 'IPV 3차', colSpan: 4 },
            {},
            {},
            { text: 'IPV 4차', colSpan: 2 },
            {},
            {},
        ],
        [
            {},
            {},
            {},
            { text: 'Hib 1차', colSpan: 1 },
            { text: 'Hib 2차', colSpan: 1 },
            { text: 'Hib 3차', colSpan: 1 },
            { text: 'Hib 4차', colSpan: 2 },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
        ],
        [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { text: '고위험군에 한하여 접종', colSpan: 5 },
        ],
        [
            {},
            {},
            {},
            { text: 'RV 1차', colSpan: 1 },
            { text: 'RV 2차', colSpan: 1 },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
        ],
        [
            {},
            {},
            {},
            { text: 'RV 1차', colSpan: 1 },
            { text: 'RV 2차', colSpan: 1 },
            { text: 'RV 3차', colSpan: 1 },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
        ],
        [
            {},
            {},
            {},
            {},
            {},
            {},
            { text: 'MMR 1차', colSpan: 2 },
            {},
            {},
            {},
            { text: 'MMR 2차', colSpan: 2 },
            {},
            {},
        ],
        [
            {},
            {},
            {},
            {},
            {},
            {},
            { text: 'VAR 1회', colSpan: 2 },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
        ],
        [
            {},
            {},
            {},
            {},
            {},
            {},
            { text: 'HepA 1~2ck', colSpan: 5 },
            {},
            {},
            {},
            {},
        ],
        [
            {},
            {},
            {},
            {},
            {},
            {},
            { text: 'IJEV 1~2차', colSpan: 4 },
            { text: 'IJEV 3차', colSpan: 1 },
            {},
            { text: 'IJEV 4차', colSpan: 1 },
            {},
            { text: 'IJEV 5차', colSpan: 1 },
        ],
        [
            {},
            {},
            {},
            {},
            {},
            {},
            { text: 'LJEV 1차', colSpan: 4 },
            { text: 'LJEV 2차', colSpan: 1 },
            {},
            {},
            {},
            {},
        ],
        [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { text: 'HPV 1~2차', colSpan: 2 },
        ],
        [{}, {}, {}, {}, {}, { text: 'IIV 매년 접종', colSpan: 10 }],
    ];

    return (
        <div
            style={{
                display: 'grid',
                gridTemplateColumns: 'repeat(15, 1fr)', // 15개의 동일한 너비의 컬럼 생성 // 1fr 말고 px ,% 등 사용 가능
                overflowX: 'auto', // 표가 화면을 벗어나면 가로 스크롤 추가
            }}
        >
            {vaccinationData.flat().map((dose, i) => (
                // flat()을 사용해 2차원 배열을 1차원 배열로 변환
                <div
                    key={i}
                    style={{
                        // colSpan 값이 있으면 해당 크기만큼 병합
                        gridColumn: dose.colSpan
                            ? `span ${dose.colSpan}`
                            : 'span 1',
                        backgroundColor: dose.text ? '#FFD700' : 'transparent',
                    }}
                >
                    {dose.text}
                </div>
            ))}
        </div>
    );
};
