import { VaccinationScheduleData } from '../types';

export const vaccinationScheduleData: VaccinationScheduleData[][] = [
    [
        { text: 'HepB 1차', vaccinationid: 1, dosenumber: 1, colSpan: 1 },
        {},
        { text: 'HepB 2차', vaccinationid: 1, dosenumber: 2, colSpan: 1 },
        {},
        {},
        { text: 'HepB 3차', vaccinationid: 1, dosenumber: 3, colSpan: 1 },
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
    ],
    [
        {},
        { text: 'BCG 1회', vaccinationid: 2, dosenumber: 1, colSpan: 1 },
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
    ],
    [
        {},
        {},
        {},
        { text: 'DTaP 1차', vaccinationid: 3, dosenumber: 1, colSpan: 1 },
        { text: 'DTaP 2차', vaccinationid: 3, dosenumber: 2, colSpan: 1 },
        { text: 'DTaP 3차', vaccinationid: 3, dosenumber: 3, colSpan: 1 },
        {},
        { text: 'DTaP 4차', vaccinationid: 3, dosenumber: 4, colSpan: 2 },
        {},
        {},
        { text: 'DTaP 5차', vaccinationid: 3, dosenumber: 5, colSpan: 2 },
        {},
        {},
    ],
    [
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        { text: 'Tdap/Td 6차', vaccinationid: 4, dosenumber: 1, colSpan: 2 },
    ],
    [
        {},
        {},
        {},
        { text: 'IPV 1차', vaccinationid: 5, dosenumber: 1, colSpan: 1 },
        { text: 'IPV 2차', vaccinationid: 5, dosenumber: 2, colSpan: 1 },
        { text: 'IPV 3차', vaccinationid: 5, dosenumber: 3, colSpan: 4 },
        {},
        {},
        { text: 'IPV 4차', vaccinationid: 5, dosenumber: 4, colSpan: 2 },
        {},
        {},
    ],
    [
        {},
        {},
        {},
        { text: 'Hib 1차', vaccinationid: 6, dosenumber: 1, colSpan: 1 },
        { text: 'Hib 2차', vaccinationid: 6, dosenumber: 2, colSpan: 1 },
        { text: 'Hib 3차', vaccinationid: 6, dosenumber: 3, colSpan: 1 },
        { text: 'Hib 4차', vaccinationid: 6, dosenumber: 4, colSpan: 2 },
        {},
        {},
        {},
        {},
        {},
        {},
        {},
    ],
    [
        {},
        {},
        {},
        { text: 'PCV 1차', vaccinationid: 7, dosenumber: 1, colSpan: 1 },
        { text: 'PCV 2차', vaccinationid: 7, dosenumber: 2, colSpan: 1 },
        { text: 'PCV 3차', vaccinationid: 7, dosenumber: 3, colSpan: 1 },
        { text: 'PCV 4차', vaccinationid: 7, dosenumber: 4, colSpan: 2 },
        {},
        {},
        {},
        {},
        {},
        {},
        {},
    ],
    [
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {
            text: '고위험군에 한하여 접종',
            vaccinationid: 8,
            dosenumber: 1,
            colSpan: 5,
        },
    ],
    [
        {},
        {},
        {},
        { text: 'RV 1차', vaccinationid: 9, dosenumber: 1, colSpan: 1 },
        { text: 'RV 2차', vaccinationid: 9, dosenumber: 2, colSpan: 1 },
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
    ],
    [
        {},
        {},
        {},
        { text: 'RV 1차', vaccinationid: 10, dosenumber: 1, colSpan: 1 },
        { text: 'RV 2차', vaccinationid: 10, dosenumber: 2, colSpan: 1 },
        { text: 'RV 3차', vaccinationid: 10, dosenumber: 3, colSpan: 1 },
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
    ],
    [
        {},
        {},
        {},
        {},
        {},
        {},
        { text: 'MMR 1차', vaccinationid: 11, dosenumber: 1, colSpan: 2 },
        {},
        {},
        {},
        { text: 'MMR 2차', vaccinationid: 11, dosenumber: 2, colSpan: 2 },
        {},
        {},
    ],
    [
        {},
        {},
        {},
        {},
        {},
        {},
        { text: 'VAR 1회', vaccinationid: 12, dosenumber: 1, colSpan: 2 },
        {},
        {},
        {},
        {},
        {},
        {},
        {},
    ],
    [
        {},
        {},
        {},
        {},
        {},
        {},
        { text: 'HepA 1~2차', vaccinationid: 13, dosenumber: 1, colSpan: 5 },
        {},
        {},
        {},
        {},
    ],
    [
        {},
        {},
        {},
        {},
        {},
        {},
        { text: 'IJEV 1~2차', vaccinationid: 14, dosenumber: 0, colSpan: 4 },
        { text: 'IJEV 3차', vaccinationid: 14, dosenumber: 3, colSpan: 1 },
        {},
        { text: 'IJEV 4차', vaccinationid: 14, dosenumber: 4, colSpan: 1 },
        {},
        { text: 'IJEV 5차', vaccinationid: 14, dosenumber: 5, colSpan: 1 },
    ],
    [
        {},
        {},
        {},
        {},
        {},
        {},
        { text: 'LJEV 1차', vaccinationid: 15, dosenumber: 1, colSpan: 4 },
        { text: 'LJEV 2차', vaccinationid: 15, dosenumber: 2, colSpan: 1 },
        {},
        {},
        {},
        {},
    ],
    [
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        { text: 'HPV 1~2차', vaccinationid: 16, dosenumber: 0, colSpan: 2 },
    ],
    [
        {},
        {},
        {},
        {},
        {},
        {
            text: 'IIV 매년 접종',
            vaccinationid: 17,
            dosenumber: 0,
            colSpan: 10,
        },
    ],
];
